# PublishDocs.ps1 - Documentation Publisher
# Publishes documentation to various formats and destinations

param(
    [string]$DocsPath = "$PSScriptRoot\..\..\Docs",
    [string]$OutputPath = "$PSScriptRoot\..\..\Published",
    [ValidateSet("HTML", "PDF", "Wiki", "All")]
    [string]$Format = "HTML",
    [switch]$Validate
)

$ErrorActionPreference = "Stop"

Write-Host "=== Documentation Publisher ===" -ForegroundColor Cyan

# Validate first if requested
if ($Validate) {
    Write-Host "Running validation..." -ForegroundColor Cyan
    & "$PSScriptRoot\ValidateDocs.ps1" -DocsPath $DocsPath
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Documentation validation failed. Fix issues before publishing."
    }
}

New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null

function Publish-HTML {
    Write-Host "`nPublishing HTML documentation..." -ForegroundColor Cyan

    $htmlPath = Join-Path $OutputPath "html"
    New-Item -ItemType Directory -Path $htmlPath -Force | Out-Null

    # Copy markdown files and convert to HTML
    $mdFiles = Get-ChildItem -Path $DocsPath -Filter "*.md" -Recurse

    foreach ($mdFile in $mdFiles) {
        $relativePath = $mdFile.FullName.Substring($DocsPath.Length + 1)
        $htmlFile = $relativePath -replace "\.md$", ".html"
        $outputFile = Join-Path $htmlPath $htmlFile

        $outputDir = Split-Path $outputFile
        New-Item -ItemType Directory -Path $outputDir -Force | Out-Null

        # Simple markdown to HTML conversion
        $content = Get-Content $mdFile.FullName -Raw
        $html = @"
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>HorrorProject Documentation</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; }
        h2 { color: #34495e; margin-top: 30px; }
        code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }
        pre { background: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; }
        a { color: #3498db; text-decoration: none; }
        a:hover { text-decoration: underline; }
    </style>
</head>
<body>
$($content -replace "\.md", ".html")
</body>
</html>
"@

        Set-Content -Path $outputFile -Value $html
    }

    Write-Host "HTML documentation published to: $htmlPath" -ForegroundColor Green
}

function Publish-Wiki {
    Write-Host "`nPreparing Wiki format..." -ForegroundColor Cyan

    $wikiPath = Join-Path $OutputPath "wiki"
    New-Item -ItemType Directory -Path $wikiPath -Force | Out-Null

    # Copy markdown files with wiki-friendly naming
    $mdFiles = Get-ChildItem -Path $DocsPath -Filter "*.md" -Recurse

    foreach ($mdFile in $mdFiles) {
        $wikiName = $mdFile.BaseName -replace " ", "-"
        $outputFile = Join-Path $wikiPath "$wikiName.md"

        Copy-Item $mdFile.FullName -Destination $outputFile
    }

    Write-Host "Wiki documentation prepared at: $wikiPath" -ForegroundColor Green
    Write-Host "Upload to GitHub Wiki or Confluence" -ForegroundColor Yellow
}

function Publish-PDF {
    Write-Host "`nChecking for PDF converter..." -ForegroundColor Cyan

    # Check for pandoc
    $pandoc = Get-Command pandoc -ErrorAction SilentlyContinue
    if (-not $pandoc) {
        Write-Warning "Pandoc not found. Install from https://pandoc.org/"
        Write-Host "Skipping PDF generation" -ForegroundColor Yellow
        return
    }

    $pdfPath = Join-Path $OutputPath "pdf"
    New-Item -ItemType Directory -Path $pdfPath -Force | Out-Null

    $mdFiles = Get-ChildItem -Path $DocsPath -Filter "*.md" -Recurse

    foreach ($mdFile in $mdFiles) {
        $pdfFile = Join-Path $pdfPath "$($mdFile.BaseName).pdf"
        & pandoc $mdFile.FullName -o $pdfFile --pdf-engine=xelatex

        if ($LASTEXITCODE -eq 0) {
            Write-Host "  Generated: $($mdFile.BaseName).pdf" -ForegroundColor Green
        }
    }

    Write-Host "PDF documentation published to: $pdfPath" -ForegroundColor Green
}

# Publish based on format
switch ($Format) {
    "HTML" { Publish-HTML }
    "PDF" { Publish-PDF }
    "Wiki" { Publish-Wiki }
    "All" {
        Publish-HTML
        Publish-PDF
        Publish-Wiki
    }
}

# Create index
$indexContent = @"
# HorrorProject Documentation

Published: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

## Available Formats

- [HTML Documentation](html/index.html)
- [Wiki Format](wiki/)
- [PDF Documents](pdf/)

## Quick Links

- [Getting Started](html/Developer/GettingStarted.html)
- [System Architecture](html/Architecture/SystemOverview.html)
- [API Reference](html/API/index.html)

---
Generated by PublishDocs.ps1
"@

Set-Content -Path (Join-Path $OutputPath "index.md") -Value $indexContent

Write-Host "`n=== Publishing Complete ===" -ForegroundColor Cyan
Write-Host "Documentation published to: $OutputPath" -ForegroundColor Green
