<#
.SYNOPSIS
    Generate Widget Blueprint templates for UMG UI
.DESCRIPTION
    Creates Widget Blueprint templates with UMG-specific structure
.PARAMETER WidgetName
    Name of the Widget Blueprint
.PARAMETER OutputPath
    Output directory
.PARAMETER WidgetType
    Type of widget (HUD, Menu, Dialog, Tooltip, etc.)
.EXAMPLE
    .\GenerateWidgetBlueprint.ps1 -WidgetName "WBP_MainMenu" -OutputPath "D:/gptzuo/HorrorProject/HorrorProject/Content/UI"
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$WidgetName,

    [Parameter(Mandatory=$true)]
    [string]$OutputPath,

    [Parameter(Mandatory=$false)]
    [ValidateSet("HUD", "Menu", "Dialog", "Tooltip", "Inventory", "Notification", "Custom")]
    [string]$WidgetType = "Custom",

    [Parameter(Mandatory=$false)]
    [switch]$IncludeAnimations,

    [Parameter(Mandatory=$false)]
    [switch]$Verbose
)

$ErrorActionPreference = "Stop"
$LogFile = Join-Path $PSScriptRoot "Logs/GenerateWidgetBlueprint_$(Get-Date -Format 'yyyyMMdd_HHmmss').log"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "[$timestamp] [$Level] $Message"
    Add-Content -Path $LogFile -Value $logMessage
    if ($Verbose -or $Level -eq "ERROR") {
        Write-Host $logMessage -ForegroundColor $(if($Level -eq "ERROR"){"Red"}elseif($Level -eq "WARN"){"Yellow"}else{"White"})
    }
}

function Get-WidgetComponents {
    param([string]$Type)

    $components = @{
        "HUD" = @("CanvasPanel", "TextBlock_Health", "ProgressBar_Health", "TextBlock_Ammo", "Image_Crosshair")
        "Menu" = @("CanvasPanel", "VerticalBox_Buttons", "Button_Start", "Button_Options", "Button_Quit", "Image_Background")
        "Dialog" = @("Border", "VerticalBox", "TextBlock_Title", "TextBlock_Message", "HorizontalBox_Buttons", "Button_Confirm", "Button_Cancel")
        "Tooltip" = @("Border", "TextBlock_Title", "TextBlock_Description")
        "Inventory" = @("CanvasPanel", "GridPanel_Items", "ScrollBox_Items", "TextBlock_ItemCount")
        "Notification" = @("Border", "HorizontalBox", "Image_Icon", "TextBlock_Message")
        "Custom" = @("CanvasPanel")
    }

    return $components[$Type]
}

function New-WidgetBlueprint {
    param(
        [string]$Name,
        [string]$Type,
        [string]$Path,
        [bool]$Animations
    )

    $guid = [guid]::NewGuid().ToString("N").ToUpper()
    $components = Get-WidgetComponents -Type $Type

    $widgetTemplate = @{
        "Type" = "WidgetBlueprint"
        "Name" = $Name
        "ParentClass" = "/Script/UMG.UserWidget"
        "WidgetType" = $Type
        "GeneratedBy" = "GenerateWidgetBlueprint.ps1"
        "GeneratedDate" = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        "GUID" = $guid
        "WidgetTree" = @{
            "RootWidget" = $components[0]
            "Components" = $components | ForEach-Object {
                @{
                    "Name" = $_
                    "Type" = $_.Split('_')[0]
                    "Properties" = @{}
                }
            }
        }
        "Variables" = @()
        "Functions" = @(
            @{
                "Name" = "Construct"
                "Type" = "Event"
                "Description" = "Called when widget is constructed"
            }
            @{
                "Name" = "Tick"
                "Type" = "Event"
                "Description" = "Called every frame"
            }
        )
        "Animations" = if ($Animations) {
            @(
                @{
                    "Name" = "FadeIn"
                    "Duration" = 0.3
                    "Tracks" = @()
                }
                @{
                    "Name" = "FadeOut"
                    "Duration" = 0.3
                    "Tracks" = @()
                }
            )
        } else { @() }
        "Metadata" = @{
            "Category" = "UI/$Type"
            "Description" = "Widget Blueprint for $Name"
            "Keywords" = "UI, Widget, UMG, $Type"
        }
    }

    $outputFile = Join-Path $Path "$Name.json"

    if (-not (Test-Path $Path)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
        Write-Log "Created directory: $Path"
    }

    $widgetTemplate | ConvertTo-Json -Depth 10 | Out-File -FilePath $outputFile -Encoding UTF8
    Write-Log "Generated Widget Blueprint: $outputFile"

    return $outputFile
}

function New-WidgetCppHeader {
    param(
        [string]$Name,
        [string]$Path
    )

    $className = $Name -replace '^WBP_', 'U'
    $headerFile = Join-Path $Path "$className.h"

    $header = @"
// Auto-generated Widget Blueprint header
// Generated by GenerateWidgetBlueprint.ps1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "$className.generated.h"

/**
 * Widget Blueprint: $Name
 */
UCLASS()
class HORRORPROJECT_API $className : public UUserWidget
{
    GENERATED_BODY()

public:
    // Constructor
    $className(const FObjectInitializer& ObjectInitializer);

protected:
    // Called when widget is constructed
    virtual void NativeConstruct() override;

    // Called when widget is destructed
    virtual void NativeDestruct() override;

    // Called every frame
    virtual void NativeTick(const FGeometry& MyGeometry, float InDeltaTime) override;

public:
    // Widget components (bind in Blueprint)
    // Add UPROPERTY(meta = (BindWidget)) for required widgets

    // Widget functions
    UFUNCTION(BlueprintCallable, Category = "UI")
    void ShowWidget();

    UFUNCTION(BlueprintCallable, Category = "UI")
    void HideWidget();

protected:
    // Internal state
    bool bIsVisible;
};
"@

    $header | Out-File -FilePath $headerFile -Encoding UTF8
    Write-Log "Generated C++ header: $headerFile"

    return $headerFile
}

# Main execution
try {
    Write-Log "Starting Widget Blueprint generation"
    Write-Log "Widget Name: $WidgetName"
    Write-Log "Widget Type: $WidgetType"
    Write-Log "Output Path: $OutputPath"

    # Create logs directory
    $logsDir = Join-Path $PSScriptRoot "Logs"
    if (-not (Test-Path $logsDir)) {
        New-Item -ItemType Directory -Path $logsDir -Force | Out-Null
    }

    # Validate widget name
    if ($WidgetName -notmatch '^(WBP_|W_)?[A-Za-z_][A-Za-z0-9_]*$') {
        throw "Invalid Widget name. Should follow WBP_ or W_ naming convention."
    }

    # Generate Widget Blueprint
    $widgetFile = New-WidgetBlueprint -Name $WidgetName -Type $WidgetType -Path $OutputPath -Animations $IncludeAnimations

    # Generate C++ header
    $headerFile = New-WidgetCppHeader -Name $WidgetName -Path $OutputPath

    Write-Log "Widget Blueprint generation completed successfully" -Level "INFO"
    Write-Host "`nGenerated files:" -ForegroundColor Green
    Write-Host "  Widget: $widgetFile" -ForegroundColor Cyan
    Write-Host "  Header: $headerFile" -ForegroundColor Cyan

    return @{
        Success = $true
        WidgetFile = $widgetFile
        HeaderFile = $headerFile
    }

} catch {
    Write-Log "Error: $($_.Exception.Message)" -Level "ERROR"
    Write-Log "Stack trace: $($_.ScriptStackTrace)" -Level "ERROR"
    throw
}
